// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskAPI.Data;

#nullable disable

namespace TaskAPI.Data.Migrations
{
    [DbContext(typeof(TodoDBContext))]
    partial class TodoDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskAPI.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Due")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 1, 6, 11, 11, 5, 912, DateTimeKind.Local).AddTicks(3587),
                            Description = "Test",
                            Due = new DateTime(2024, 1, 8, 11, 11, 5, 912, DateTimeKind.Local).AddTicks(3596),
                            Status = 0,
                            Title = "Db record 1"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2024, 1, 6, 11, 11, 5, 912, DateTimeKind.Local).AddTicks(3603),
                            Description = "Test2",
                            Due = new DateTime(2024, 1, 8, 11, 11, 5, 912, DateTimeKind.Local).AddTicks(3604),
                            Status = 0,
                            Title = "Db record 2"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2024, 1, 6, 11, 11, 5, 912, DateTimeKind.Local).AddTicks(3605),
                            Description = "Test3",
                            Due = new DateTime(2024, 1, 8, 11, 11, 5, 912, DateTimeKind.Local).AddTicks(3605),
                            Status = 0,
                            Title = "Db record 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
